export const MODULE_CLIENT_TOKEN = 'STORAGE_BLOB_CLIENT';
export const MODULE_OPTIONS_TOKEN = 'STORAGE_BLOB_OPTIONS';
export const MODULE_CONNECTION_VARIABLE_TOKEN = 'NESTJS_STORAGE_BLOB_CONNECTION_VARIABLE';
